version: '3'

services:
  redis-server:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      calculator-network:

  calculator-server:
    container_name: calculator-service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis-server
    networks:
      calculator-network:

networks:
  calculator-network: